# Generated by Django 4.2.13 on 2024-06-10 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('describe', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('important', models.IntegerField(blank=True, choices=[(1, 'Urgente'), (2, 'Alta'), (3, 'Média'), (4, 'Baixa')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
